#ifndef COMMONWIDGETSAPI_H
#define COMMONWIDGETSAPI_H
#include <QtCore/QtGlobal>


#if defined(COMMONWIDGETS_BUILD)
#define COMMONWIDGETS_API    Q_DECL_EXPORT
#else
#define  COMMONWIDGETS_API
#endif

//Q_DECL_IMPORT.
#endif // COMMONWIDGETSAPI_H
